version: '3'

services:
  python-app:
    stop_grace_period: 30s
    build:
      context: .
      dockerfile: Dockerfile
    image: python-app-image
    environment:
      - THREAD_LIMIT=2
    volumes:
      - $PWD/data:/app/data
    restart: unless-stopped
